name: Build and deploy PHP app via FTP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Defina a versão do PHP conforme necessário

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Upload Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .
