name: Build and deploy PHP app via FTP

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Defina a versão do PHP conforme necessário

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Upload Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .
    
  deploy:
      runs-on: ubuntu-latest
      needs: build
  
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: php-app
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Upload via FTP
          uses: milanmk/actions-file-deployer@master
          with:
            remote-protocol: sftp
            remote-host: ${{ secrets.FTP_SERVIDOR }}
            remote-user: ${{ secrets.FTP_USUARIO }}
            remote-path: ${{ secrets.FTP_PASTA }}
            remote-port: ${{ secrets.FTP_PORTA }}
            sync: ${{ secrets.FTP_TIPO_SYNC }}
            remote-password: ${{ secrets.FTP_SENHA }}
            local-path: ./
            artifacts: true
